name: Deploy Next.js to Google Cloud VM

on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: 35.223.104.63
          username: ${{ secrets.GCP_VM_USER }}
          key: ~/.ssh/id_rsa
          source: "."
          target: "/home/finance/nextjs-beginner"

      - name: Run Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: 35.223.104.63
          username: ${{ secrets.GCP_VM_USER }}
          key: ~/.ssh/id_rsa
          script: |
            cd /home/finance/nextjs-beginner
            git pull origin main
            npm install
            npm run build
            pm2 restart all
